### ISSUE TITLE
Openstreetmap web fails to boot because "Could not locate Gemfile or .bundle/ directory"

### ISSUE THREAD

**Issue by xhluca** [gasse/webarena-setup#3]
running the instructions in step 3 of readme: https://github.com/gasse/webarena-setup/blob/main/webarena/03_docker_create_containers.sh

I realize the container does not start. running `sudo docker logs <container_name>`, I find that:

```
Could not locate Gemfile or .bundle/ directory
```

**Comment by xhluca** [comment]
I manually connected via `sudo docker run -it openstreetmap-website-web bash` and tried to run `bundle exec rails s -p 3000 -b '0.0.0.0'` but got the exact error as above. It appears that if I `cd /app`, the command still doesn't work. Unfortunately `cd` does not work as a command

**Comment by gasse** [comment]
Script 03 does not start the containers, it just creates them. Did you run script 04 as well?

I had issues with openstreetmaps in the past, but this one is new to me. You can try to isolate the problem by installing the openstreetmap docker only, and see which step fails

```sh
# from https://github.com/gasse/webarena-setup/blob/main/webarena/01_docker_load_images.sh#L45-L51

# extract openstreetmap archive locally (if needed)
if [ ! -d ./openstreetmap-website ]; then
  echo "Extracting openstreemap archive..."
  tar -xzf ${ARCHIVES_LOCATION}/openstreetmap-website.tar.gz
else
  echo "Openstreemap archive already extracted."
fi

# from https://github.com/gasse/webarena-setup/blob/main/webarena/02_docker_remove_containers.sh

docker stop openstreetmap-website-db-1 openstreetmap-website-web-1
docker remove openstreetmap-website-db-1 openstreetmap-website-web-1

# from https://github.com/gasse/webarena-setup/blob/main/webarena/03_docker_create_containers.sh#L16-L19

cd openstreetmap-website/
cp ../openstreetmap_docker-compose.yml.template docker-compose.yml
sed -i "s|MAP_PORT|${MAP_PORT}|g" docker-compose.yml
docker compose create

# from https://github.com/gasse/webarena-setup/blob/main/webarena/04_docker_start_containers.sh

cd openstreetmap-website/
docker compose start

# from https://github.com/gasse/webarena-setup/blob/main/webarena/05_docker_patch_containers.sh

docker exec openstreetmap-website-web-1 bin/rails db:migrate RAILS_ENV=development

```

**Comment by xhluca** [comment]
Seems like it works when I run the instructions like that, but somehow when I run the 05*.sh script it fails. I will look into it, it might be caused by port changes or the fact i'm assigning an environment name. Will keep you updated

**Comment by xhluca** [comment]
Here's the image when i follow the instructions above, for some reason the tiles do not show up. did ytou have this probelm?

<img width="1463" alt="image" src="https://github.com/user-attachments/assets/ef438485-4ddb-4f61-b124-e88ef96b38d3">

**Comment by xhluca** [comment]
actually i'm not sure if the patching worked:

```
>>> sudo docker exec openstreetmap-website-web-1 bin/rails db:migrate RAILS_ENV=development

warning: parser/current is loading parser/ruby30, which recognizes 3.0.6-compliant syntax, but you are running 3.0.2.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through options)
advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
optipng worker: `optipng` not found; please provide proper binary or disable this worker (--no-optipng argument or `:optipng => false` through options)
pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
jhead worker: `jhead` not found, `jpegtran` not found; please provide proper binary or disable this worker (--no-jhead argument or `:jhead => false` through options)
jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
jpegtran worker: `jpegtran` not found; please provide proper binary or disable this worker (--no-jpegtran argument or `:jpegtran => false` through options)
gifsicle worker: `gifsicle` not found; please provide proper binary or disable this worker (--no-gifsicle argument or `:gifsicle => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
```

**Comment by gasse** [comment]
I get all those not found errors as well, I think they re ok. Not sure about the warning in the first line though.

**Comment by xhluca** [comment]
I'm making progress!

Quick question: Why are we downloading 3 tar.gz files:


```
wget https://zenodo.org/records/12636845/files/openstreetmap-website-db.tar.gz
wget https://zenodo.org/records/12636845/files/openstreetmap-website-web.tar.gz
wget https://zenodo.org/records/12636845/files/openstreetmap-website.tar.gz
```

When only one is untared? 

```
tar -xzf ./openstreetmap-website.tar.gz
```

**Comment by xhluca** [comment]
Ok, after trying the exact instructions shared in [this comment](https://github.com/gasse/webarena-setup/issues/3#issuecomment-2515472039), I found that it is once again blank: 
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/67161d67-0457-4a10-bf64-d5b68246a3f0">

I am re-reading the `webarena/environment_docker` README and found that they are requiring containers for the Geocoding, Tile and Routing servers (3 containers) alongside more files to download (a few GB each). Is that covered in the instructions here?

**Comment by xhluca** [comment]
It seems that I simply needed to change the layer to "Humanitarian" and the map appeared! I guess that was selected by default in the envrionment, hence i was not able to do it. I think it should work now after testing one example, will close for now

**Comment by gasse** [comment]
Hi Xing, I'm trying on my side, I also end up with an empty map. What did you do exactly to make it work? How did you change the layer to "Humanitarian" ?

![Screenshot 2024-12-05 at 3 21 49 PM](https://github.com/user-attachments/assets/75d2a57f-3430-4ac1-b996-3c3b0f55635b)

**Comment by gasse** [comment]
Oh I found it, it seems to change the background but doesn't load the roads and places though. I'll re-open and investigate more

**Comment by xhluca** [comment]
You are right. There seems to be some issue, I just looked at the agent run on agentxray from my localsetup and the screenshot don't work properly.

What do your screenshots look like?

### webarena.8 (seed: 23)
| AWS | Local |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/2cccce9b-62bd-469c-8647-d574e2b4a5f7) |  ![image](https://github.com/user-attachments/assets/4e039ad5-ec91-454f-99ec-185c12498d9b) |

### webarena.9 (seed: 23)

![image](https://github.com/user-attachments/assets/b9ddc53e-b93f-4fdd-a818-71b51902bf03)

### webarena.764 (seed: 13)

In this case it actually succeed!

![image](https://github.com/user-attachments/assets/6b989466-a810-4aa9-adf1-23d7ae19c2c3)

**Comment by xhluca** [comment]
What's interesting is that the same "blank" state appears for the aws version, yet on the xray app, i see that the map appears properly using the "humanitarian" layer. Could there be some "reset" code that switches to the layer?

**Comment by xhluca** [comment]
@gasse I think I found the solution.

All we need is to add `&layers=H` to the end of the URL.

Strangely enough, it is not automatically added when it's on localhost, e.g. https://127.0.0.1:$MAP_PORT

However, once i set up cloudflare, it is automatically added at the end, e.g. https://map.url-to-webarena.com/#map=7/42.888/-75.103&layers=H

I will look into it further.

**Comment by leixy20** [comment]
@gasse @xhluca 
hi, firstly thanks for the discussion ! 

I encountered the same issue(empty map) and i think the issue stems from this file: openstreetmap-website/vendor/assets/leaflet/leaflet.osm.js, which configures the resource tile server for each layer.
The original configuration is url: 'http://ogma.lti.cs.cmu.edu:8080/tile/{z}/{x}/{y}.png' and maybe the server is unstable or even sometimes down. 

So the simplest solution is to change this into the official tile server of openstreetmap: url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'. It worked in my attempt and the standard layer of the map appeared after changing the server. Further, webarena environment provides guidance on deploying the tile server locally, the guide is here: https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md#tile-sever.

I hope it will help you.

**Comment by xhluca** [comment]
@leixy20 that's very interesting! I will look into this.

Do you think we need to set up the geolocation and routing servers too?

**Comment by xhluca** [comment]
Ok I just noticed something subtle in this file:

[fossgis_osrm.js.txt](https://github.com/user-attachments/files/18087528/fossgis_osrm.js.txt)

here:

```js
// ...
      var vehicleTypePortMapping = {
        "car": "5000",
        "bike": "5001",
        "foot": "5002"
      }

      // var req_url = OSM.FOSSGIS_OSRM_URL + "routed-" + vehicleType + "/route/v1/driving/" + encoded_coords;
      var req_url = OSM.FOSSGIS_OSRM_URL + vehicleTypePortMapping[vehicleType] + "/route/v1/driving/" + encoded_coords;
// ...
```

It appears this is code added by the authors of webarena to force the request URL to map to a port rather than a `/routed-{car, foot, bike}` URL subpath. So that part would also need to be modified.

Btw I opened a PR to udpate the docs thanks to your suggestions @leixy20: https://github.com/web-arena-x/webarena/pull/190

**Comment by leixy20** [comment]
Yeah, I have also noticed this file. I set up the routing server locally, and btw in my attempt, the url is not properly configured. I have to change the url to:
```
var req_url = OSM.FOSSGIS_OSRM_URL + vehicleTypePortMapping[vehicleType] + "/route/v1/" + vehicleType + "/" + encoded_coords;
```
This url works for the routing server i deployed following instructions in webarena: https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md#routing-server

**Comment by xhluca** [comment]
Interesting. It seems to not make a difference for the default url, i.e. routing.openstreetmap.de

For example, both of the following urls map to the same json:

https://routing.openstreetmap.de/routed-bike/route/v1/bike/-79.94926619122354,40.4413599;-79.9416735939551,40.4263827?overview=false&geometries=polyline&steps=true&hints=vGjbgmXAAIYDAAAArgAAAAcBAAAuAAAAabDGP756kELsF9tCpDeYQQMAAACuAAAABwEAAC4AAABUBQAAOhI8-x0WaQIuEjz7EBZpAgMAHxNMq3_X;MDwCj2o8Ao9bAAAABQEAAAAAAAAAAAAApyNzQWH3LUIAAAAAAAAAAFsAAAAFAQAAAAAAAAAAAABUBQAApy88-_zbaALWLzz7j9toAgAAfwRMq3_X

https://routing.openstreetmap.de/routed-bike/route/v1/driving/-79.94926619122354,40.4413599;-79.9416735939551,40.4263827?overview=false&geometries=polyline&steps=true&hints=vGjbgmXAAIYDAAAArgAAAAcBAAAuAAAAabDGP756kELsF9tCpDeYQQMAAACuAAAABwEAAC4AAABUBQAAOhI8-x0WaQIuEjz7EBZpAgMAHxNMq3_X;MDwCj2o8Ao9bAAAABQEAAAAAAAAAAAAApyNzQWH3LUIAAAAAAAAAAFsAAAAFAQAAAAAAAAAAAABUBQAApy88-_zbaALWLzz7j9toAgAAfwRMq3_X

**Comment by gasse** [comment]
> Quick question: Why are we downloading 3 tar.gz files:
> 
> ```
> wget https://zenodo.org/records/12636845/files/openstreetmap-website-db.tar.gz
> wget https://zenodo.org/records/12636845/files/openstreetmap-website-web.tar.gz
> wget https://zenodo.org/records/12636845/files/openstreetmap-website.tar.gz
> ```
> 
> When only one is untared?
> 
> ```
> tar -xzf ./openstreetmap-website.tar.gz
> ```

The other two are docker images, they are used by the `docker-compose`. These images were not provided in the WebArena README, so what I did was extract them from their AWS image, along with the `openstreetmap-website` folder.

The images are loaded in the 01 script
https://github.com/gasse/webarena-setup/blob/main/webarena/01_docker_load_images.sh#L42-L43

**Comment by xhluca** [comment]
Weird, when i do:

```
sudo docker exec -it wa_openstreetmap_web_az_0 bash
root@93fad25680ba:/app#    
```

it goes to "/app", but in the case of @gasse it's "/". Also shm fills up quickly for me, but it shouldn't be the case!

**Comment by xhluca** [comment]
@gasse there seems to be another openstreetmap issue. On AWS, the search works:

![image](https://github.com/user-attachments/assets/5cf7f5e5-5738-46ed-b97e-23011d49c27e)

It appears that on self-hosted, it doesn't, as the /api endpoint does not seem to be set up properly.
